# Unique project identifier
sonar.projectKey=Instant_CTF
sonar.projectName=Instant_CTF
sonar.projectVersion=1.0

# Path to the source code (usually current directory)
sonar.sources=.
sonar.python.version=3.12

# Exclude directories you don't want to analyze
sonar.exclusions=**/migrations/**, **/venv/**, **/static/**, manage.py

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# (Optional) Link to your coverage report if using pytest-cov
# sonar.python.coverage.reportPaths=coverage.xml
